apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gh-template-tf-workspaces-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
      value: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    dag:
      tasks:
      - name: terraform
        arguments:
          parameters:
          - name: git_ref_type
            value: "{{ inputs.parameters.git_ref_type }}"
          - name: git_repo
            value: https://github.com/bradfordwagner/gh-template-tf-workspaces.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: terraform_image
            value: quay.io/bradfordwagner/terraform:1.7.1-ubuntu_focal
          - name: csi_class
            value: sp-infra
          - name: csi_secret
            value: sp-infra
          # name of terraform workspace
          - name: workspace_name
            value: "{{ item.name }}"
          # path in repository to use as entrypoint
          - name: workspace_path
            value: "{{ item.path }}"
        templateRef:
          name: flavor-terraform-template
          template: main
        withItems:
          - name: dev
            path: ./environments/dev
          - name: tst
            path: ./environments/tst

